### ISSUE TITLE
Score-Based Model Support

### ISSUE THREAD

**Issue by jacobchristopher** [joaoamcarvalho/mpd-public#4]
Hi @jacarvalho,

The current code based includes several score-based model architectures, which were explored in your previous work and to a lesser degree in the paper associated with this code base. Is there intent to provide support for these models as well in this repository? While many of the elements necessary to use these models seem to be included, I have not found all of the referenced utility functions used by these models. Namely, the helper file `mpd.models.helpers.marginal_prob` is absent from the codebase, which is referenced by `ScoreModelBase`, and perhaps others that I missed. 

Thanks!

**Comment by joaoamcarvalho** [comment]
Hey,
We initially started this project with score-based models but moved to diffusion models since they were easier to train. What you encountered was some code left from the initial experimentation that I forgot to clean it from the repository - I'm sorry for that!
So in short, we don't plan to add the support for score-based models.
